### ISSUE TITLE
How to collect repositories by user folders?

### ISSUE THREAD

**Issue by ZhukovLabs** [gabrielcsapo/node-git-server#112]
Hello.
How to collect repositories by user folders?
I use node-git-server and express together.
Code:
```javascript
import express from "express";
import path from "path";
import {Git} from 'node-git-server';

const __dirname = path.resolve();
const reposPath = path.join(__dirname, 'repos');

const app = express();

const repos = new Git(reposPath, {
    autoCreate: true,
});

repos.on('push', (push) => {
    console.log(`push ${push.repo}/${push.commit} ( ${push.branch} )`);
    push.accept();
});

repos.on('fetch', (fetch) => {
    console.log(`fetch ${fetch.commit}`);
    fetch.accept();
});


app.use((req, res, next) => {
    console.log(req.url)
    next();
})

app.use("/:account/:repo", (req, res) => {
    repos.handle(req, res);
})

app.listen(8000, () => {
    console.log(`Express http server listening`);
});
``` 
It doesn't work. 
![image](https://user-images.githubusercontent.com/49492348/225922129-6bbe2ace-4c2b-408e-b9f7-430469950807.png)
The request comes and goes to handle, but something goes wrong there?

It works: 
```javascript
app.use("/:repo", (req, res) => {
    repos.handle(req, res);
})
``` 

```
git push http://localhost:8000/git/beep master
``` 

But it without account name and url has superfluous endpoint "/git"
I will add the user to the path without changing the endpoint
```
git push http://localhost:8000/git/somebody/beep master
``` 
![image](https://user-images.githubusercontent.com/49492348/225924671-5509baf0-78ae-4257-a9e6-a8b3619d1302.png)
It works! But "/git" need it.
Lets try delete it.
```
git push http://localhost:8000/somebody/beep master
``` 
Now repo inside repos, not inside the user folder. It's bad (
![image](https://user-images.githubusercontent.com/49492348/225925004-cedb508a-3cc6-4317-8b13-a643f062dee3.png)

Lets try change endpoint:
```javascript
app.use("/:account/:repo", (req, res) => {
    repos.handle(req, res);
})
``` 
```
git push http://localhost:8000/somebody/beep master
``` 
It does't work (

It doens't work too:
```
git push http://localhost:8000/git/somebody/beep master
``` 

Help me please. I want to make a git server where the user will be. And user repositories should be in folders with their names.

**Comment by ZhukovLabs** [comment]
Use without endpoint:
```javascript
app.use((req, res) => {
    repos.handle(req, res);
})
``` 
```
git push http://localhost:8000/somebody/beep master
``` 

It works. But...
![image](https://user-images.githubusercontent.com/49492348/225927783-49e9e1e7-da47-467b-ba9a-27d5e1494388.png)
2 folders are created. One is empty. And the global endpoint is not very suitable

Also I try use this endpoint:
```javascript
app.use("/git/:repo", (req, res) => {
    repos.handle(req, res);
})
``` 
``` 
git push http://localhost:8000/git/somebody/beep master
```
User folder not created =(

**Comment by ZhukovLabs** [comment]
Some one? =(

**Comment by verside2** [comment]
> Some one? =(

Use translator from Russian to English if you need.

Данный странный эффект проявляется из-за использования `url.parse(req.url)` в исходных кодах библиотеки, который объявлен Deprecated в документации nodejs: по каким-то причинам данная функция превращает путь `/git/beep/info/refs?service=git-receive-pack` в `/beep/info/refs?service=git-receive-pack`, т. е. урезая первую часть. В причины я уже не стал углубляться, но решение может быть таким (если не менять исходные коды самой библиотеки):

```js
app.use("/:account/:repo", (req, res) => {
    req.url = req.originalUrl;

    repos.handle(req, res);
});
```

**Comment by ZhukovLabs** [comment]
Спасибо, это помогло =)

**Comment by Denis-Zhukov** [comment]
Это помогло, но всё также создаёт пустую папку(проблема описана выше)
![image](https://user-images.githubusercontent.com/49492348/230228480-61c65941-44f6-48b3-9cff-9d55377ac928.png)
