### ISSUE TITLE
add a web interface to the repos? 

### ISSUE THREAD

**Issue by gabrielcsapo** [gabrielcsapo/node-git-server#12]
Would be interesting to see how much would be needed to create something like https://gogs.io or https://github.com or even https://bitbucket.org 🤔

**Comment by plunkettscott** [comment]
I don't think this would actually be that hard. Doubt it would need to be super in-depth like Github.

**Comment by gabrielcsapo** [comment]
@plunkettscott I definitely want to have all the functionality needed to build something like github, but you are right, the web interface could be very simple.

**Comment by plunkettscott** [comment]
How are you thinking of connecting the two? Commands ran in the background from the web client, or, wrapping the commands around RESTful endpoints?

**Comment by gabrielcsapo** [comment]
wrapping the commands around restful endpoints. All of the git commands should go through node-git-server and then should in turn trigger events or save data.

**Comment by gabrielcsapo** [comment]
@plunkettscott what kind of restful commands are you talking about? theoretically any restful endpoints should be communicating with a database, not the commands directly, right?

**Comment by plunkettscott** [comment]
Something similar to https://github.com/korya/node-git-rest-api, but cleaned up and refactored a bit. That's the kind RESTful endpoints I am talking about. I do believe that this one is backed by the commands. There are no databases involved. However, for a GUI I'd assume you'd want to include a database (especially if you are managing users).

**Comment by gabrielcsapo** [comment]
@plunkettscott that might be a little bit out of scope, github exposes api's to work with the git repos, but a true git server would just allow administration and extensions via the interface, not the rest endpoints.

**Comment by jlxip** [comment]
This would really improve the package. I hope you can do it. Good luck!

**Comment by gabrielcsapo** [comment]
@jlxip still looking into finding time, but if we could do this it could mean a super lightweight git-server deployable anywhere.

**Comment by jlxip** [comment]
@gabrielcsapo 
What a coincidence, I'm trying to make this very project a bit more "uncomplicated", today I released a new version to npm. However, there are no docs yet. Here, have a look: https://github.com/jlxip/UltraGit

Every data (users, repositories and permissions) are stored in a database, this way it can be managed with a browser. It's still in progress though.

**Comment by gabrielcsapo** [comment]
@jlxip that is awesome! I look forward to seeing what you come up with! Let me know if I can help in any way.

**Comment by echopoint** [comment]
No idea how many people are looking to work together on a ui but if we do, let's choose a framework to do so, huh? ;)

**Comment by gabrielcsapo** [comment]
@echopoint I am down! I like react, really good DX, small footprint with 16.0, but I also think something like https://github.com/mde/ejs or even no framework using template strings. What do you think @echopoint?

**Comment by echopoint** [comment]
I was thinking mith for a react like setup but with a small dependency that's fast

**Comment by jlxip** [comment]
Are you going to base the UI in this package or in UltraGit (with users data in a database)?

**Comment by echopoint** [comment]
Ultragit is external to this project.  There were probably somewhere around 3 or 4 plans for the ui already but we're just coming together on it now. Tbh this can go with a simple sqlite interface instead of a full blown mariadb / postgres type.. If we're really going for something like gittea then that would probably be the best as it's small, light and fast and keeps it contained.

**Comment by jlxip** [comment]
How are you going to connect to a DB with no dependencies?

**Comment by echopoint** [comment]
sqlite is one form and there isn't a need of an sql db or an external db server to handle that job

**Comment by jlxip** [comment]
But what I don't understand is what is wrong with using dependencies. They are the base of Node.js, aren't they?

**Comment by echopoint** [comment]
I can't answer for @gabrielcsapo but for me it's because they break, become unmaintained, increase download time and unneeded bloat

**Comment by jlxip** [comment]
By the way, thanks for recommending SQLite, I haven't used it before, and it's about time to start.

**Comment by gabrielcsapo** [comment]
@echopoint I agree with your sentiment. Packages are super useful for bootstrapping and idea, but all projects should be focused on reducing the complexity and reusing as much native logic to accomplish those tasks. 

@echopoint any thoughts on no framework and simply using server rendered views just as most of the git clients do it? Low overhead from a client perspective and logic can be contained internally rather than expressive through API's that might be single purposed.

**Comment by plunkettscott** [comment]
I'd feel better building it in a framework WITH an API, rather than from
within. That API could come in handy for other things later on, or, could
get use outside of the UI.

**Comment by gabrielcsapo** [comment]
I agree, but there are things that could cause the API to bloat to get simple elements rendered for a view. I am down for working on the UI in any framework, thoughts on creating a new repo rather than contribute here? I have been trying to come up with a name just as good as gitea, gogs, github, bitbucket, gitlab, nothing good has come to mind.

**Comment by plunkettscott** [comment]
I say it is a new repo, yeah.

**Comment by gabrielcsapo** [comment]
Any thoughts on a name?

**Comment by plunkettscott** [comment]
I am not very creative when it comes to naming things. Ha -- I'd say we
could go for something like Gitman or similar. Needs to be short and
concise.

**Comment by echopoint** [comment]
First ones to come to my mind were GitBit, BitGit, nGit, outside of that for now I'm blank on a name. As for frameworks, I'm fine with none too. Frameworks in this sense for me means just js frameworks and not so much UI only like bootstrap and the like. Frameworks like react or mithril, even angular aren't hard to make at all. People just don't because it's a time sinc or they just don't know how. Though one thing that will help is to know if this is going to be an SPA (single page app) or just a normal web site like bitbucket. For an SPA most js frameworks either help a bit or become a hindrance themselves, hence if one is needed I'd side with the smallest / fastest. ;)

**Comment by echopoint** [comment]
LiteGit, Grit? :)  Agreed, interface packages build up fast, so we'll just include the bare essentials and not do the whole, "we have 3 wysiwygs to handle everything". Done web for too long to have a preference over 'app' or 'webpage' anymore esp with node because people are blurring the lines more and more these days. i.e. ElectronJs and the like.

**Comment by gabrielcsapo** [comment]
@echopoint I agree, I see it everyday, brings in an entire package to just create a button 🙄. I like Grit, or Groffee 😆

**Comment by gabrielcsapo** [comment]
Oh man now I like both Grit and Groffee! @echopoint @plunkettscott @jlxip votes?

**Comment by jlxip** [comment]
@gabrielcsapo What are those?

**Comment by gabrielcsapo** [comment]
@jlxip potential names for the package for the UI

**Comment by jlxip** [comment]
I would go for **node-git-server-webui**. But that's what I would do. If I had to choose between _Grit_ and _Groffee_ I think I would go for _Groffee_.

**Comment by gabrielcsapo** [comment]
Okay since Grit is taken, I am going to go with Groffee!

**Comment by gabrielcsapo** [comment]
it has been done! 

- https://github.com/gabrielcsapo/groffee 
- https://www.npmjs.com/package/groffee

I am more than happy to add people as contributors and eventually if we can get this in a good place move it to an org! #excited

**Comment by jlxip** [comment]
First star!

**Comment by gabrielcsapo** [comment]
started another issue for discussion here https://github.com/gabrielcsapo/groffee/issues/2
