### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by plunkettscott** [gabrielcsapo/node-git-server#15]
I see that you include authentication, and upon passing the following object to the Node Git Server constructor, my requests both with and without a password are not requiring the password. 

Here's what my object looks like. Let me know if I am just doing it wrong:

```
const Options = {
    autoCreate: false,
    repos: {
      reponame: {
        username: 'myUsername',
        password: 'myPassword'
      }
    }
  }

  const Git = new Server('./repos', Options)
```
I also have listeners for a few events currently.

```
Git.on('push', (push) => {
    console.log('push ' + push.repo + '/' + push.commit
        + ' (' + push.branch + ')'
    );
    push.accept();
  })

  Git.on('fetch', (fetch) => {
    console.log(fetch)
    console.log('fetch ' + fetch.commit);
    fetch.accept();
  })
```

I've also got the following to actually start this...

```
Git.listen(Port, () => {
    app.log.info('Git Services are running.')
  })
```

What am I doing wrong, here? I see where it should be telling me I am unauthorized, however, it does not do so.

**Comment by gabrielcsapo** [comment]
@plunkettscott looking at the code it was a bug in both the parsing of the remote name and the tests that were meant to ensure basic authentication worked properly. I fixed this in 0.2.1 https://github.com/gabrielcsapo/node-git-server/releases/tag/0.2.1 🚀 would you be able to install and verify that it works properly?

**Comment by plunkettscott** [comment]
Absolutely. Give me a few and I'll update.

**Comment by plunkettscott** [comment]
Worked like a charm. Thanks for all your help!

**Comment by gabrielcsapo** [comment]
Thanks for reporting the bug! Do you have any features that you would want added? @plunkettscott

**Comment by plunkettscott** [comment]
I'm actually looking to integrate it with database authentication directly from a Loopback model. I was about to start working on that. Essentially, it's the same thing. I would just have to search for the repo, and check if the passed user/password has access to it. 

A way to split out authentication would be nice, so that you don't have to rewrite it to use it. Like, a callback function, event, or something to do authentication and return true or false with whether they can access or not. The JSON object of username/password isn't too secure and isn't very handy when you keep adding repositories. Have to restart each time you add one with users. 

The ability to implement your own authentication strategy would be preferred.

**Comment by gabrielcsapo** [comment]
@plunkettscott I can easily do that, let me write something up really quickly.

The integration would look something like:

```
git.on('authenticate', (repo, username, password, next) => {
    // if next is called with an error that will be passed back to the client
    // if next is called without an error the request will go through the flow as usual
})
```

**Comment by plunkettscott** [comment]
That'll do it!

**Comment by gabrielcsapo** [comment]
@plunkettscott actually what do you think about

```javascript
new Server(path.resolve(__dirname, 'tmp'), {
    autoCreate: true,
    repos: {
        'test': {
            username: 'admin',
            password: 'root'
        }
    },
    authenticate: (repo, username, password, next) => {}
});
```

**Comment by plunkettscott** [comment]
I like that better than through the event, actually.

**Comment by gabrielcsapo** [comment]
it will be done! @plunkettscott should get something working in the next hour or so.

**Comment by plunkettscott** [comment]
Sounds good. No rush. If you need any help let me know.

**Comment by gabrielcsapo** [comment]
@plunkettscott if you are building a GUI interface for this, I would definitely be interested in helping :)

**Comment by plunkettscott** [comment]
We are looking to integrate this into a product. Just in the testing/implementation stage. However, I'd be interested in working on a GUI for sure.

**Comment by plunkettscott** [comment]
There was a really cool package I saw awhile back (sadly, not maintained anymore) that implemented Git via REST. So, you could POST to an endpoint changes to files, commits, etc. Was really cool. I've always thought about creating one of those. RESTful endpoints for Git make integration into other projects that much easier.

**Comment by gabrielcsapo** [comment]
@plunkettscott okay! well if you are interested I will keep you in mind, I was hoping to create something  but all the names I came up with are already taken, gitea, github, gitlab, something along those lines I was thinking about gita, but that just sounds like someone's name.

**Comment by plunkettscott** [comment]
I'll try to think about names.

**Comment by gabrielcsapo** [comment]
@plunkettscott thoughts on this https://github.com/gabrielcsapo/node-git-server/pull/16 this will now remove the default authentication model and allow the user to add their own middleware to handle it.

**Comment by plunkettscott** [comment]
Are you going to pass the error message back to the client on that?

**Comment by gabrielcsapo** [comment]
@plunkettscott let me see how the client responds to custom messages

**Comment by gabrielcsapo** [comment]
<img width="471" alt="screen shot 2017-09-16 at 7 19 06 pm" src="https://user-images.githubusercontent.com/1854811/30517437-fef3ffa2-9b13-11e7-9600-cdc3c87d85b2.png">

@plunkettscott seems like it works right out of the box. I updated the PR!

**Comment by plunkettscott** [comment]
One more suggestion. What if you passed the event? For example, might enable a certain user to clone but not push, etc...

**Comment by gabrielcsapo** [comment]
@plunkettscott good idea! let me see if we can parse the event string since it comes through as `/doom.git/git-receive-pack`

**Comment by gabrielcsapo** [comment]
@plunkettscott until git client actually initializes the request, all the server knows is if it is an upload or download, I can pass that through, would that be good enough?

**Comment by plunkettscott** [comment]
Hmm.. I suppose, yeah. You can pretty much judge what is going to happen if it is an upload or download. What about terminating the request after it has hit one of the event handlers? So, tacking on authentication at `push.accept()` in the form of, they are authorized to upload they get to the push event. I see the user, and check. The user is NOT authorized to push, so I `push.decline()`.

Basically all we would need is the user passed through to that point. If it got to that point they would be authorized through authentication. Would passing the user to those events be possible?

**Comment by gabrielcsapo** [comment]
<img width="478" alt="screen shot 2017-09-16 at 7 56 04 pm" src="https://user-images.githubusercontent.com/1854811/30517576-1b9fae9e-9b19-11e7-9c7a-cfdd89925619.png">

@plunkettscott super easy, just need to parse the basic auth headers when the subsequent request comes through.

**Comment by plunkettscott** [comment]
@gabrielcsapo It sounds like this will definitely make authentication so much easier. Thanks for your hard word on this!
