### ISSUE TITLE
Allow returning a promise from the authenticate function

### ISSUE THREAD

**Issue by OmgImAlexis** [gabrielcsapo/node-git-server#18]
Instead of requiring the user to use the `next()` I'd like to return a Promise that resolves or rejects based on the user's details. The easiest way to add this is to count the params, 4 params means they're using a promise and 5 means they're using a callback.

For example.

```js
const repos = new Server('/tmp/repos', {
    authenticate: (type, repo, username, password) => {
        return new Promise(async (resolve, reject) => {
            const user = await User.findOne(username, password).exec();

            if (user.isAdmin) {
                return resolve();
            }

            if (user.isSuspended) {
                return reject(new Error('User account is suspended.'));
            }

            resolve();
        });
    }
});
```

**Comment by gabrielcsapo** [comment]
@OmgImAlexis what would be the benefit to this rather than simply passing `next` either true or false, and then an added error message? Something like:

```js
authenticate: (type, repo, username, password, next) => {
  // auth logic
  next(false, 'you are not authorized to access this resource')
}
```

**Comment by OmgImAlexis** [comment]
[You should never mix promises with callbacks](https://spin.atomicobject.com/2017/04/06/nodejs-promises-callbacks/) if you can help it and there's no real downside to adding support for it.

**Comment by gabrielcsapo** [comment]
The implementation would mix promises and callbacks if this was added.

**Comment by OmgImAlexis** [comment]
The user wouldn't be required to mix them though which is what I was hoping for.

**Comment by gabrielcsapo** [comment]
Makes sense, let me write something up really quickly @OmgImAlexis

**Comment by gabrielcsapo** [comment]
thoughts on https://github.com/gabrielcsapo/node-git-server/pull/20? @OmgImAlexis
