### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by oscartbeaumont** [gabrielcsapo/node-git-server#33]
Does this module have https support?

**Comment by jlxip** [comment]
Personally I don't need this. And I would vote against it. In my opinion, all NodeJS instances should pass by another program, such as NGINX, before going out to the internet. It's much easier to configure SSL/TLS in NGINX than in any other program. And you can have subdomains easily for every instance of NodeJS.

**Comment by echopoint** [comment]
It currently doesn't create an https connection by default. Though, it wouldn't be hard or a bad idea to add, just small set of extra config parameters would be needed. When I get a little more time I'll add it and push a PR for it.

**Comment by gabrielcsapo** [comment]
@oscartbeaumont as @jlxip said there are better ways to deal with SSL traffic, but the ability to do such things would make this library better. @echopoint are you will to pick this up or you want me to take a go at it?

**Comment by echopoint** [comment]
If you want to hammer it out first I won't be offended. I just don't know if I can get to it this week.

**Comment by gabrielcsapo** [comment]
@echopoint let me see what I can do, I will keep updating this thread with progress, if you don't see me comment anything I have made no progress 😆

**Comment by oscartbeaumont** [comment]
I am going to build this feature today and do a pull request when I am done.

**Comment by oscartbeaumont** [comment]
The other thing is can I modify the example server in the README.MD to import the path module so that the code works without changing it? Also do you want an example of https adding under that in the README or somewhere else?

**Comment by jlxip** [comment]
@oscartbeaumont That'd be good hahaha. I had to write the line that imports ```path``` every time I copy-pasted.

**Comment by oscartbeaumont** [comment]
I have done a pull request on my changes.

**Comment by echopoint** [comment]
See PR #35

**Comment by gabrielcsapo** [comment]
added in https://github.com/gabrielcsapo/node-git-server/pull/35
