### ISSUE TITLE
Error: spawn git-upload-pack ENOENT running command git-upload-pack

### ISSUE THREAD

**Issue by netlander** [gabrielcsapo/node-git-server#36]
When running a fresh install on Win 10, the commit goes well but I get the above error after trying to access the repo:
```
$ git clone http://localhost:7005/repo-test master
Cloning into 'master'...
fatal: unable to access 'http://localhost:7005/repo-test/': Recv failure: Connection was reset
```

The error coming from the server:

```
fetch repo-test
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: spawn git-upload-pack ENOENT running command git-upload-pack --stateless-rpc --advertise-refs G:\src\web\portal-development\demos\node-git-server-master\example\tmp\repo-test
    at ChildProcess.ps.on (G:\src\web\portal-development\demos\node-git-server-master\lib\util.js:90:29)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

Any pointers as to what is going wrong?

Thanks

**Comment by jlxip** [comment]
Could you paste the code you are running?

**Comment by netlander** [comment]
It's the code straight out from `example/index.js` found in the repo. I have created my own certificates and the created repos can be found in `examples/tmp`
```
// You Can Use The Commands Below To Generate A Self Signed Certificate For Use With This Tutorial
// These Commands Require That You have 'openssl' installed on your system
// openssl genrsa -out privatekey.pem 1024
// openssl req -new -key privatekey.pem -out certrequest.csr
// openssl x509 -req -in certrequest.csr -signkey privatekey.pem -out certificate.pem

let type = 'http';

process.argv.slice(2).forEach((arg) => {
  switch(arg) {
    case 'https':
    case '--https':
      type = 'https';
    break;
  }
});

const fs = require('fs');
const path = require('path');

const Server = require('../');

const port = process.env.PORT || 7005;

const repos = new Server(path.normalize(path.resolve(__dirname, 'tmp')), {
    autoCreate: true,
    authenticate: (type, repo, user, next) => {
      console.log(type, repo); // eslint-disable-line
      if(type == 'push') {
        user((username, password) => {
          console.log(username, password); // eslint-disable-line
          next();
        });
      } else {
        next();
      }
    }
});

repos.on('push', (push) => {
    console.log(`push ${push.repo} / ${push.commit} ( ${push.branch} )`); // eslint-disable-line
    repos.list((err, result) => {
        console.log(result); // eslint-disable-line
    });
    push.accept();
});

repos.on('fetch', (fetch) => {
    console.log(`username ${fetch.username}`); // eslint-disable-line
    console.log(`fetch ${fetch.repo}/${fetch.commit}`); // eslint-disable-line
    fetch.accept();
});

repos.listen(port, {
  type,
  key: fs.readFileSync('./privatekey.pem'),
  cert: fs.readFileSync('./certificate.pem')
}, (error) => {
    if(error) return console.error(`failed to start git-server because of error ${error}`); // eslint-disable-line
    console.log(`node-git-server running at ${type}://localhost:${port}`); // eslint-disable-line
    repos.list((err, result) => {
        if (!result) {
            console.log("No repositories available..."); // eslint-disable-line
        } else {
            console.log(result); // eslint-disable-line
        }
    });
});
```

**Comment by jlxip** [comment]
Works on my machine. These are the steps I followed:

- Copy and paste your code in an empty directory (```/tmp/a/index.js```).
- Changed ```const Server = require('../');``` to ```const Server = require('node-git-server');```.
- Run in the directory: ```npm install node-git-server```.
- Run: ```openssl genrsa -out privatekey.pem 1024```.
- Run: ```openssl req -new -key privatekey.pem -out certrequest.csr```.
- Run: ```openssl x509 -req -in certrequest.csr -signkey privatekey.pem -out certificate.pem```.
- Create a directory called ```tmp``` and enter it (```/tmp/a/tmp```).
- Create a directory called ```asdf``` and enter it (```/tmp/a/tmp/asdf```).
- Run: ```git init --bare```.
- Go back to ```/tmp/a```.
- Run ```node index.js```.

It ran without errors.

Now, in another terminal:
- Create an empty directory (```/tmp/b```) and enter it.
- Run: ```git clone http://localhost:7005/asdf```
(It should be OK so far.)
- Access the cloned ```asdf``` directory.
- Create a random commit to initialize the repository:
-- Run: ```echo a>a.txt```
-- Run: ```git add *```
-- Run: ```git commit -m a```
-- Run: ```git push``` with random username and password.
(It should be OK so far.)
- Delete the cloned repository with ```rm -rf /tmp/b/asdf```
- Clone it again with: ```git clone http://localhost:7005/asdf```.
- Enter the directory.
- Run: ```cat a.txt```

Everything seems to be working fine. Try it, and if it doesn't work, the problem probably has to do with your NodeJS installation.

**Comment by gabrielcsapo** [comment]
Thank you so much @jlxip for helping @netlander with his issue! Really thorough instructions. @netlander did these help? If so I think we could add these to the docs so that anyone else facing this issue can refer back to this for help.

**Comment by netlander** [comment]
@gabrielcsapo @jlxip Just trying these now... Will update later (probably tomorrow).

**Comment by netlander** [comment]
The above instructions didn't work for me. In fact I tried something similar before opening this issue but when I try to do `npm i node-git-server` inside the repo, I get the following error, which is the same error I got when I tried the above steps.

```
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "node-git-server" under a package
npm ERR! also called "node-git-server". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yaseen\AppData\Roaming\npm-cache\_logs\2018-03-06T13_34_56_108Z-debug.log
```

**You need to amend the documentation to make it clear that users can use the given example either in a fresh node project or an existing one but outside of this repo.**
