### ISSUE TITLE
Q: Can you write more data to client http connection?

### ISSUE THREAD

**Issue by stevepeak** [gabrielcsapo/node-git-server#37]
I would like to write data back to client after a `push` event. I could not find a clear way to do this:

```node
repos.on('push', (push) => {
  push.accept();
  push.client.write('---> Building Application.')
  // ...
  push.client.write('Done.')
})
```
> Think of this like `git push heroku master` for deploying code. Heroku outputs the build logs during the push command.

```
$ git push foobar master

Counting objects: 3, done.
Writing objects: 100% (3/3), 633 bytes | 633.00 KiB/s, done.
Total 3 (delta 0), reused 3 (delta 0)
To http://localhost:7005/beep
 * [new branch]      master -> master

---> Building Application.
Done.
```

Thanks 🙏

**Comment by stevepeak** [comment]
Thanks! 😄 I tried the `push.client.write()` (I think it was) but there is an issue requiring you to chunk the data yourself. A simple way may be to expose a new method that does this for you automatically.

Full spec of what I'm looking for:
1. Write streaming event logs to the client.
2. Reject the push if there are issues during the accepting period
3. Call my own external method that yields output

Would be great to do this:
```node
repos.on('push', (push) => {
  push.accept(function(push, client){
     // repo.git is uploaded
     client.write('---> Building');
     try {
        // do some long operations
        client.write('     Done.');
      }
      catch(error) {
        console.error(error);
        throw ("Failed to build");
      }
  });
})
```

**Comment by gabrielcsapo** [comment]
ohhh, that is interesting, so push is overloaded with the client stream?

> shouldn't it look like

```js
repos.on('push', (push) => {
  push.accept(function(client){
     // repo.git is uploaded
     client.write('---> Building\n');
     try {
        // do some long operations
        client.write('     Done.\n');
      }
      catch(error) {
        console.error(error);
        throw ("Failed to build");
      }
  });
})
```

**Comment by gabrielcsapo** [comment]
Still looking for a good solution, I might have to rethink a some things, also the git additional text protocol is super confusing -_-

**Comment by gabrielcsapo** [comment]
so after tons of research, we can only send sideband data to the client when done through `info` and not on an upload-pack... which means sending data via the push is not possible from what I am seeing / endless trying to implement.

**Comment by gabrielcsapo** [comment]
> Hold on, I think I just figured something out... 💻

**Comment by xanf** [comment]
For those, who are looking for solution like me, here comes a code to get you started:

```js
const pack = s => {
  const n = (4 + s.length).toString(16);
  return Array(4 - n.length + 1).join('0') + n + s;
};

repos.on('push', push => {
  push.on('response', function captureStream(str) {
    this.once('exit', () => {
      const SIDEBAND = String.fromCharCode(2); // PROGRESS
      const message = `${SIDEBAND}hello long long long\n`;
      const formattedMessage = Buffer.from(pack(message));
      str.queue(formattedMessage);
      str.queue(Buffer.from('0000'));
      str.queue(null);
    });
  });

  console.log(`push ${push.repo}/${push.commit} (${push.branch})`);
  push.accept();
});
```

**Comment by gabrielcsapo** [comment]
@xanf will look into putting this into an API you can call thanks for this 🎉

**Comment by gabrielcsapo** [comment]
after months of this being an issue https://github.com/gabrielcsapo/node-git-server/releases/tag/0.5.0 we have landed 🚀

**Comment by xanf** [comment]
Yay :)
