### ISSUE TITLE
How to Merge on Push 

### ISSUE THREAD

**Issue by Waterloo** [gabrielcsapo/node-git-server#42]

**Comment by gabrielcsapo** [comment]
@Waterloo would you be able to give more context to the issue?

**Comment by gabrielcsapo** [comment]
Are you asking for something like what a PR is on github?

**Comment by colbygilbert95** [comment]
Not sure what the above question is but it would be cool to know how to do a pull request like on github

**Comment by gabrielcsapo** [comment]
@colbygilbert95 GitHub just compares two remote branches together. When you click merge is just merges one remote into the other. I really want to make a UI for this in https://github.com/gabrielcsapo/groffee... ☕️
