### ISSUE TITLE
0.5.0 release not published

### ISSUE THREAD

**Issue by mojavelinux** [gabrielcsapo/node-git-server#47]
The 0.5.0 release was tagged, but there's no corresponding package on npm / yarnpkg. Is this intentional? If not, could you publish it?

**Comment by gabrielcsapo** [comment]
@mojavelinux will publish when I get home, I don't know why it wasn't published...

**Comment by mojavelinux** [comment]
Thanks!

**Comment by gabrielcsapo** [comment]
@mojavelinux `0.5.0` is published ✨

**Comment by mojavelinux** [comment]
Thanks again!

I can confirm that the change in this release allows node-git-server to be used on Windows. You can see it in action here: https://gitlab.com/antora/antora/pipelines/39416545

**Comment by gabrielcsapo** [comment]
thanks @mojavelinux!
