### ISSUE TITLE
pass headers into authenticate

### ISSUE THREAD

**Issue by pyramation** [gabrielcsapo/node-git-server#49]
Would be great if the `authenticate` method had access to request headers. Looks like it wouldn't be terribly hard since the req object is already right there: https://github.com/gabrielcsapo/node-git-server/blob/62b1cb6079cad19b51d4ca7f7d85c48bcc22ed5d/lib/git.js#L305

**Comment by gabrielcsapo** [comment]
Thanks for looking into the PR @pyramation, it is released in 0.6.0 🚀
