### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by akif-ih** [gabrielcsapo/node-git-server#63]
@gabrielcsapo 
How could i do initial commit, like i want to create a readmd 
which i did in this way
 const child = spawn(`touch README.md | echo $'# ${repoName}/n${description}' > README.md | git add . | git commit -m "Initial Commit" |  git push origin master`, {
            shell: true,
            cwd: path.resolve(__dirname, `../../repos/${username}/${repoName}.git`)
        })

but it says

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Git.js:59error: src refspec master does not match any.
error: failed to push some refs to 'origin'

**Comment by gabrielcsapo** [comment]
Git works based on a single access, and when a thread has access to the git file it will create a lock. This ensures there is no fragmentation. To ensure you can do this simple change your | to && as this will make sure it happens in sequence.
