### ISSUE TITLE
Authentication is not working

### ISSUE THREAD

**Issue by rivenblades** [gabrielcsapo/node-git-server#64]
This example you have in the site doesnt do authenticat when i push a commit.
it just hangs
https://www.npmjs.com/package/node-git-server#authentication

**Comment by damiendawreck** [comment]
I have been running into the same problem. I figured it out by adding next("Invalid credentials"); whenever the credentials are wrong. That seems to fix the issue.

**Comment by gabrielcsapo** [comment]
Thank you @damiendawreck for answering this question, closing this out as it seems like the right solution to move forward with.
