### ISSUE TITLE
Repo link generates an SSL error

### ISSUE THREAD

**Issue by chmac** [gabrielcsapo/node-git-server#68]
This repo links to https://www.gabrielcsapo.com/node-git-server/

This in turn generates an SSL error because the certificates are not valid for this domain. Removing the `www.` from the domain fixes the issue.

Changing the URL would likely be the simplest fix, otherwise maybe you wanna add www support.

**Comment by gabrielcsapo** [comment]
Thank you! Should be fixed, I had GitHub custom domains misconfigured.
