### ISSUE TITLE
Typescript types?

### ISSUE THREAD

**Issue by chmac** [gabrielcsapo/node-git-server#70]
Firstly, thanks for this package. It looks like a nice and simple way to get started with a git hosting server.

Is there any interest / intention in adding typescript types? I started hacking a bit, and could share that if it's useful. Just not sure if you have any interest in adding the types or not.

**Comment by mattwynne** [comment]
@chmac I'd be interested in using these, and collaborating on them with you.

Do you have a fork you can push?

**Comment by gabrielcsapo** [comment]
Would be more than happy to give ownership for adding types!

**Comment by chmac** [comment]
@gabrielcsapo Are you open to reviewing / merging PRs? I submitted a couple of minor documentation changes which are currently open. #72 and #73 I think.

I ended up publishing the package under my own namespace as `@chmac/node-git-server` as I needed some of my changes immediately in my own project. I'd prefer to withdraw my version if you're open to accepting PRs, etc.

@mattwynne You can see the types that I'm using [here](https://github.com/GenerousLabs/plans/blob/master/server/src/modules.d.ts). I'm pretty sure the types are incomplete. 

My TypeScript fu is pretty weak, but I'd be happy to collaborate on the types if you're open to that. I guess there's probably a way to build the types from the existing JSDoc comments somehow. I'm not sure how that would work, I haven't looked into it, but it seems like it should somehow be an option. Ideally we'd have a single source of truth that way.

My modules file was the quickest hack I could come up with to be able to use this code with types inside my project. Oh yeah, and it includes some options that I added to fit my use case. I think I submitted PRs for them all, but haven't had any feedback on those yet, so unclear if these types will ever fit this project, etc, etc...

**Comment by gabrielcsapo** [comment]
@chmac will look at these open PRs today and merge.

**Comment by gabrielcsapo** [comment]
@chmac would you be interested in opening up a pr to add types?

**Comment by chmac** [comment]
Quick follow up to say I found this in my inbox today, sorry for the outrageously slow reply, which also makes it clear that I won't get to this task any time soon.

**Comment by gabrielcsapo** [comment]
Types have been added, thanks for those involved @5GameMaker !

**Comment by gabrielcsapo** [comment]
https://github.com/gabrielcsapo/node-git-server/pull/88
