### ISSUE TITLE
Authenticate on clone

### ISSUE THREAD

**Issue by asifashraf** [gabrielcsapo/node-git-server#77]
The authentication example on readme looks good for push commands. But I can clone any random name and this will create a new repo automatically anonymously? If auto creating is doing that which is great, where is authentication in that?

**Comment by aral** [comment]
Just add a check for `type === fetch'` in the code that triggers your authentication:

```
    if (type === 'push' || type === 'fetch') {
      user((accountName, password) => {
        console.log('Authenticating:', accountName, password)
        next()
      })
    } else {
      next()
    }
```

**Comment by gabrielcsapo** [comment]
Thanks for answering @aral, closing.
