### ISSUE TITLE
Support all kinds of refs, not just branches and tags

### ISSUE THREAD

**Issue by mattwynne** [gabrielcsapo/node-git-server#82]
We had a need to be able to push arbitrary refs, not just branches and tags. (See https://github.com/SmartBear/git-en-boite/issues/217#issuecomment-708627474)

I made this hack to get it to work for us:
https://github.com/SmartBear/node-git-server/commit/2dceb3bbac9a40cbfdaacf65b3d807731cd7e85e

However, I'm sure this will have broken something, as I can see assumptions in the code where it expects the ref to either be a branch or a tag. Fortunately it doesn't seem to have broken anything we were relying on in our own test suite.

Are you interested in merging this change in? I'd prefer to only be using our own fork temporarily.

If so, can you coach me how to add tests for it, and with any other changes that might be needed to make it work without breaking the existing API?

**Comment by gabrielcsapo** [comment]
I am 100% in favor of merging this in!

Once you have PR up I can help write tests with you.

**Comment by mattwynne** [comment]
OK cool!

I made the PR #83, so let's move the discussion over there.
